import "./globals.css";
import Layout from "./components/layout";
import { ShoppingCartContextProvider } from "./Context/ShoppingCartContext";
import { FilterProvider } from "./Context/FilterShoppingContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ShoppingCartContextProvider>
        <FilterProvider> 
          <Layout>{children}</Layout>
        </FilterProvider>
      </ShoppingCartContextProvider>

      </body>
    </html>
  );
}
